version: '3'
services:
  # RabbitMQ Docker
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: unless-stopped
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - erestorannet
 
#mssql docker
  erestoran-sql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    restart: unless-stopped
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=test12!W
      - MSSQL_PID=Developer
    ports:
      - 1433:1433
    expose:
      - 1433
    networks:
      - erestorannet
 
  erestoran-api:
    restart: unless-stopped
    build:
      context: .
    environment:
      - ConnectionStrings__DefaultConnection=Server=erestoran-sql,1433;Database=eRestoran;User Id=sa;Password=test12!W;ConnectRetryCount=0;TrustServerCertificate=True
      - ASPNETCORE_ENVIRONMENT=Development
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USERNAME=guest
      - RABBITMQ_PASSWORD=guest
      - SMTP_SERVER=smtp.outlook.com
      - SMTP_PORT=587
      - SMTP_USERNAME=testkorisnik.fit@gmail.com
      - SMTP_PASSWORD=test12PASS!
    ports:
      - 7003:7003
    networks:
      - erestorannet
    links:
      - erestoran-sql
    depends_on:
      - erestoran-sql
      - rabbitmq
 
        # RabbitMQ Service Docker
  rabbitmq-service:
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./eRestoran.Subscriber/Dockerfile
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USERNAME=guest
      - RABBITMQ_PASSWORD=guest
      - SMTP_SERVER=smtp.outlook.com
      - SMTP_PORT=587
      - SMTP_USERNAME=testkorisnik.fit@gmail.com
      - SMTP_PASSWORD=test12PASS!
    depends_on:
      - rabbitmq
    networks:
      - erestorannet
     
networks:
  erestorannet:
    driver: bridge    
