// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using eRestoran.Services.Database;

#nullable disable

namespace eRestoran.Services.Migrations
{
    [DbContext(typeof(ERestoranContext))]
    [Migration("20230811092544_SM")]
    partial class SM
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("eRestoran.Services.Database.Dojmovi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("JeloId")
                        .HasColumnType("int");

                    b.Property<int?>("KorisnikId")
                        .HasColumnType("int");

                    b.Property<int?>("Ocjena")
                        .HasColumnType("int");

                    b.Property<string>("Opis")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id")
                        .HasName("PK__Dojmovi__3214EC078DD4709C");

                    b.HasIndex("JeloId");

                    b.HasIndex("KorisnikId");

                    b.ToTable("Dojmovi", (string)null);
                });

            modelBuilder.Entity("eRestoran.Services.Database.Drzava", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Naziv")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id")
                        .HasName("PK__Drzava__3214EC076CFB6820");

                    b.ToTable("Drzava", (string)null);
                });

            modelBuilder.Entity("eRestoran.Services.Database.Grad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Naziv")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id")
                        .HasName("PK__Grad__3214EC07EA4B5287");

                    b.ToTable("Grad", (string)null);
                });

            modelBuilder.Entity("eRestoran.Services.Database.Jelo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("Cijena")
                        .HasColumnType("money");

                    b.Property<int?>("KategorijaId")
                        .HasColumnType("int");

                    b.Property<string>("Naziv")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Opis")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Slika")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id")
                        .HasName("PK__Jelo__3214EC0766C6F668");

                    b.HasIndex("KategorijaId");

                    b.ToTable("Jelo", (string)null);
                });

            modelBuilder.Entity("eRestoran.Services.Database.Kategorija", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Naziv")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Opis")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id")
                        .HasName("PK__Kategori__3214EC070A4F4900");

                    b.ToTable("Kategorija", (string)null);
                });

            modelBuilder.Entity("eRestoran.Services.Database.Korisnici", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("DrzavaId")
                        .HasColumnType("int");

                    b.Property<int?>("GradId")
                        .HasColumnType("int");

                    b.Property<string>("Ime")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("KorisnickoIme")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LozinkaHash")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LozinkaSalt")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("Prezime")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id")
                        .HasName("PK__Korisnic__3214EC07033A56BF");

                    b.HasIndex("DrzavaId");

                    b.HasIndex("GradId");

                    b.ToTable("Korisnici", (string)null);
                });

            modelBuilder.Entity("eRestoran.Services.Database.KorisniciUloge", b =>
                {
                    b.Property<int>("KorisnikUlogaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KorisnikUlogaId"));

                    b.Property<DateTime>("DatumIzmjene")
                        .HasColumnType("datetime");

                    b.Property<int>("KorisnikId")
                        .HasColumnType("int");

                    b.Property<int>("UlogaId")
                        .HasColumnType("int");

                    b.HasKey("KorisnikUlogaId")
                        .HasName("PK__Korisnic__1608726E77415232");

                    b.HasIndex("KorisnikId");

                    b.HasIndex("UlogaId");

                    b.ToTable("KorisniciUloge", (string)null);
                });

            modelBuilder.Entity("eRestoran.Services.Database.Narudzba", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DatumNarudzbe")
                        .HasColumnType("datetime");

                    b.Property<int?>("KorisnikId")
                        .HasColumnType("int");

                    b.Property<string>("StateMachine")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("StatusNarudzbeId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Narudzba__3214EC07423966FD");

                    b.HasIndex("KorisnikId");

                    b.HasIndex("StatusNarudzbeId");

                    b.ToTable("Narudzba", (string)null);
                });

            modelBuilder.Entity("eRestoran.Services.Database.Status", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Naziv")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id")
                        .HasName("PK__Status__3214EC071A49A4A8");

                    b.ToTable("Status", (string)null);
                });

            modelBuilder.Entity("eRestoran.Services.Database.StavkeNarudzbe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Cijena")
                        .HasColumnType("int");

                    b.Property<int?>("JeloId")
                        .HasColumnType("int");

                    b.Property<int?>("Kolicina")
                        .HasColumnType("int");

                    b.Property<int?>("NarudzbaId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__StavkeNa__3214EC0781E952BB");

                    b.HasIndex("JeloId");

                    b.HasIndex("NarudzbaId");

                    b.ToTable("StavkeNarudzbe", (string)null);
                });

            modelBuilder.Entity("eRestoran.Services.Database.Uloge", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Naziv")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Opis")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id")
                        .HasName("PK__Uloge__3214EC076C332449");

                    b.ToTable("Uloge", (string)null);
                });

            modelBuilder.Entity("eRestoran.Services.Database.Uplatum", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BrojTransakcije")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<DateTime?>("DatumTransakcije")
                        .HasColumnType("datetime");

                    b.Property<decimal?>("Iznos")
                        .HasColumnType("money");

                    b.Property<int?>("KorisnikId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Uplata__3214EC07C865A4BE");

                    b.HasIndex("KorisnikId");

                    b.ToTable("Uplata");
                });

            modelBuilder.Entity("eRestoran.Services.Database.Dojmovi", b =>
                {
                    b.HasOne("eRestoran.Services.Database.Jelo", "Jelo")
                        .WithMany("Dojmovis")
                        .HasForeignKey("JeloId")
                        .HasConstraintName("FK__Dojmovi__JeloId__36B12243");

                    b.HasOne("eRestoran.Services.Database.Korisnici", "Korisnik")
                        .WithMany("Dojmovis")
                        .HasForeignKey("KorisnikId")
                        .HasConstraintName("FK__Dojmovi__Korisni__37A5467C");

                    b.Navigation("Jelo");

                    b.Navigation("Korisnik");
                });

            modelBuilder.Entity("eRestoran.Services.Database.Jelo", b =>
                {
                    b.HasOne("eRestoran.Services.Database.Kategorija", "Kategorija")
                        .WithMany("Jelos")
                        .HasForeignKey("KategorijaId")
                        .HasConstraintName("FK__Jelo__Kategorija__2E1BDC42");

                    b.Navigation("Kategorija");
                });

            modelBuilder.Entity("eRestoran.Services.Database.Korisnici", b =>
                {
                    b.HasOne("eRestoran.Services.Database.Drzava", "Drzava")
                        .WithMany("Korisnicis")
                        .HasForeignKey("DrzavaId")
                        .HasConstraintName("FK__Korisnici__Drzav__29572725");

                    b.HasOne("eRestoran.Services.Database.Grad", "Grad")
                        .WithMany("Korisnicis")
                        .HasForeignKey("GradId")
                        .HasConstraintName("FK__Korisnici__GradI__286302EC");

                    b.Navigation("Drzava");

                    b.Navigation("Grad");
                });

            modelBuilder.Entity("eRestoran.Services.Database.KorisniciUloge", b =>
                {
                    b.HasOne("eRestoran.Services.Database.Korisnici", "Korisnik")
                        .WithMany("KorisniciUloges")
                        .HasForeignKey("KorisnikId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Korisnici__Koris__4316F928");

                    b.HasOne("eRestoran.Services.Database.Uloge", "Uloga")
                        .WithMany("KorisniciUloges")
                        .HasForeignKey("UlogaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Korisnici__Uloga__440B1D61");

                    b.Navigation("Korisnik");

                    b.Navigation("Uloga");
                });

            modelBuilder.Entity("eRestoran.Services.Database.Narudzba", b =>
                {
                    b.HasOne("eRestoran.Services.Database.Korisnici", "Korisnik")
                        .WithMany("Narudzbas")
                        .HasForeignKey("KorisnikId")
                        .HasConstraintName("FK__Narudzba__Korisn__32E0915F");

                    b.HasOne("eRestoran.Services.Database.Status", "StatusNarudzbe")
                        .WithMany("Narudzbas")
                        .HasForeignKey("StatusNarudzbeId")
                        .HasConstraintName("FK__Narudzba__Status__33D4B598");

                    b.Navigation("Korisnik");

                    b.Navigation("StatusNarudzbe");
                });

            modelBuilder.Entity("eRestoran.Services.Database.StavkeNarudzbe", b =>
                {
                    b.HasOne("eRestoran.Services.Database.Jelo", "Jelo")
                        .WithMany("StavkeNarudzbes")
                        .HasForeignKey("JeloId")
                        .HasConstraintName("FK__StavkeNar__JeloI__3A81B327");

                    b.HasOne("eRestoran.Services.Database.Narudzba", "Narudzba")
                        .WithMany("StavkeNarudzbes")
                        .HasForeignKey("NarudzbaId")
                        .HasConstraintName("FK__StavkeNar__Narud__3B75D760");

                    b.Navigation("Jelo");

                    b.Navigation("Narudzba");
                });

            modelBuilder.Entity("eRestoran.Services.Database.Uplatum", b =>
                {
                    b.HasOne("eRestoran.Services.Database.Korisnici", "Korisnik")
                        .WithMany("Uplata")
                        .HasForeignKey("KorisnikId")
                        .HasConstraintName("FK__Uplata__Korisnik__3E52440B");

                    b.Navigation("Korisnik");
                });

            modelBuilder.Entity("eRestoran.Services.Database.Drzava", b =>
                {
                    b.Navigation("Korisnicis");
                });

            modelBuilder.Entity("eRestoran.Services.Database.Grad", b =>
                {
                    b.Navigation("Korisnicis");
                });

            modelBuilder.Entity("eRestoran.Services.Database.Jelo", b =>
                {
                    b.Navigation("Dojmovis");

                    b.Navigation("StavkeNarudzbes");
                });

            modelBuilder.Entity("eRestoran.Services.Database.Kategorija", b =>
                {
                    b.Navigation("Jelos");
                });

            modelBuilder.Entity("eRestoran.Services.Database.Korisnici", b =>
                {
                    b.Navigation("Dojmovis");

                    b.Navigation("KorisniciUloges");

                    b.Navigation("Narudzbas");

                    b.Navigation("Uplata");
                });

            modelBuilder.Entity("eRestoran.Services.Database.Narudzba", b =>
                {
                    b.Navigation("StavkeNarudzbes");
                });

            modelBuilder.Entity("eRestoran.Services.Database.Status", b =>
                {
                    b.Navigation("Narudzbas");
                });

            modelBuilder.Entity("eRestoran.Services.Database.Uloge", b =>
                {
                    b.Navigation("KorisniciUloges");
                });
#pragma warning restore 612, 618
        }
    }
}
