// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using eRestoran.Services.Database;

#nullable disable

namespace eRestoran.Services.Migrations
{
    [DbContext(typeof(ERestoranContext))]
    [Migration("20241029115528_nacinPlacanja")]
    partial class nacinPlacanja
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("eRestoran.Services.Database.Dojmovi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("JeloId")
                        .HasColumnType("int");

                    b.Property<int?>("KorisnikId")
                        .HasColumnType("int");

                    b.Property<int?>("Ocjena")
                        .HasColumnType("int");

                    b.Property<string>("Opis")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id")
                        .HasName("PK__Dojmovi__3214EC078DD4709C");

                    b.HasIndex("JeloId");

                    b.HasIndex("KorisnikId");

                    b.ToTable("Dojmovi", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 8000,
                            JeloId = 5000,
                            KorisnikId = 1002,
                            Ocjena = 5,
                            Opis = "odlicna dostava"
                        });
                });

            modelBuilder.Entity("eRestoran.Services.Database.Drzava", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Naziv")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id")
                        .HasName("PK__Drzava__3214EC076CFB6820");

                    b.ToTable("Drzava", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 2000,
                            Naziv = "Bosna i Hercegovina"
                        },
                        new
                        {
                            Id = 2001,
                            Naziv = "Njemacka"
                        });
                });

            modelBuilder.Entity("eRestoran.Services.Database.Grad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Naziv")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id")
                        .HasName("PK__Grad__3214EC07EA4B5287");

                    b.ToTable("Grad", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 3000,
                            Naziv = "Sarajevo"
                        });
                });

            modelBuilder.Entity("eRestoran.Services.Database.Jelo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("Cijena")
                        .HasColumnType("money");

                    b.Property<int?>("KategorijaId")
                        .HasColumnType("int");

                    b.Property<string>("Naziv")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Opis")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<byte[]>("Slika")
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("SlikaThumb")
                        .HasColumnType("varbinary(max)");

                    b.HasKey("Id")
                        .HasName("PK__Jelo__3214EC0766C6F668");

                    b.HasIndex("KategorijaId");

                    b.ToTable("Jelo", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 5000,
                            Cijena = 15m,
                            KategorijaId = 4000,
                            Naziv = "Margarita",
                            Opis = "top"
                        });
                });

            modelBuilder.Entity("eRestoran.Services.Database.Kategorija", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Naziv")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Opis")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id")
                        .HasName("PK__Kategori__3214EC070A4F4900");

                    b.ToTable("Kategorija", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 4000,
                            Naziv = "Pizza",
                            Opis = "top"
                        },
                        new
                        {
                            Id = 4001,
                            Naziv = "Rostilj",
                            Opis = "top"
                        },
                        new
                        {
                            Id = 4002,
                            Naziv = "Pasta",
                            Opis = "top"
                        },
                        new
                        {
                            Id = 4003,
                            Naziv = "Desert",
                            Opis = "top"
                        });
                });

            modelBuilder.Entity("eRestoran.Services.Database.Korisnici", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("DrzavaId")
                        .HasColumnType("int");

                    b.Property<int?>("GradId")
                        .HasColumnType("int");

                    b.Property<string>("Ime")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("KorisnickoIme")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LozinkaHash")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("LozinkaSalt")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Prezime")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id")
                        .HasName("PK__Korisnic__3214EC07033A56BF");

                    b.HasIndex("DrzavaId");

                    b.HasIndex("GradId");

                    b.ToTable("Korisnici", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1001,
                            Ime = "Medzida",
                            KorisnickoIme = "admin",
                            LozinkaHash = "qIasZbaXQkHV6Gs14MLy37WIhrU=",
                            LozinkaSalt = "FMsIo5+6IjlaCw4Ko3KKWA==",
                            Prezime = "Bojcic"
                        },
                        new
                        {
                            Id = 1002,
                            Ime = "Ena",
                            KorisnickoIme = "mobile",
                            LozinkaHash = "1FAKiuzbDt43bdYieXeE7ri/i4g=",
                            LozinkaSalt = "3pYEFkl0vFcOCY3w6Fa9Eg==",
                            Prezime = "Bojcic"
                        });
                });

            modelBuilder.Entity("eRestoran.Services.Database.KorisniciUloge", b =>
                {
                    b.Property<int?>("KorisnikUlogaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("KorisnikUlogaId"));

                    b.Property<DateTime?>("DatumIzmjene")
                        .HasColumnType("datetime");

                    b.Property<int?>("KorisnikId")
                        .HasColumnType("int");

                    b.Property<int?>("UlogaId")
                        .HasColumnType("int");

                    b.HasKey("KorisnikUlogaId")
                        .HasName("PK__KorisniciUloge__1608726E");

                    b.HasIndex("KorisnikId");

                    b.HasIndex("UlogaId");

                    b.ToTable("KorisniciUloge", (string)null);

                    b.HasData(
                        new
                        {
                            KorisnikUlogaId = 1,
                            DatumIzmjene = new DateTime(2024, 10, 29, 12, 55, 28, 511, DateTimeKind.Local).AddTicks(5516),
                            KorisnikId = 1001,
                            UlogaId = 1
                        },
                        new
                        {
                            KorisnikUlogaId = 2,
                            DatumIzmjene = new DateTime(2024, 10, 29, 12, 55, 28, 511, DateTimeKind.Local).AddTicks(5555),
                            KorisnikId = 1002,
                            UlogaId = 2
                        });
                });

            modelBuilder.Entity("eRestoran.Services.Database.Narudzba", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DatumNarudzbe")
                        .HasColumnType("datetime");

                    b.Property<int?>("KorisnikId")
                        .HasColumnType("int");

                    b.Property<string>("StateMachine")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("StatusNarudzbeId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Narudzba__3214EC07423966FD");

                    b.HasIndex("KorisnikId");

                    b.HasIndex("StatusNarudzbeId");

                    b.ToTable("Narudzba", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 6000,
                            DatumNarudzbe = new DateTime(2024, 10, 29, 12, 55, 28, 511, DateTimeKind.Local).AddTicks(5623),
                            KorisnikId = 1001,
                            StateMachine = "poslano",
                            StatusNarudzbeId = 8010
                        });
                });

            modelBuilder.Entity("eRestoran.Services.Database.Status", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Naziv")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id")
                        .HasName("PK__Status__3214EC071A49A4A8");

                    b.ToTable("Status", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 8010,
                            Naziv = "poslano"
                        });
                });

            modelBuilder.Entity("eRestoran.Services.Database.StavkeNarudzbe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Cijena")
                        .HasColumnType("int");

                    b.Property<int?>("JeloId")
                        .HasColumnType("int");

                    b.Property<int?>("Kolicina")
                        .HasColumnType("int");

                    b.Property<int?>("NarudzbaId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__StavkeNa__3214EC0781E952BB");

                    b.HasIndex("JeloId");

                    b.HasIndex("NarudzbaId");

                    b.ToTable("StavkeNarudzbe", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 7000,
                            Cijena = 30,
                            JeloId = 5000,
                            Kolicina = 2,
                            NarudzbaId = 6000
                        });
                });

            modelBuilder.Entity("eRestoran.Services.Database.Uloge", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Naziv")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Opis")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id")
                        .HasName("PK__Uloge__3214EC076C332449");

                    b.ToTable("Uloge", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Naziv = "Admin",
                            Opis = "Upravljanje sistemom"
                        },
                        new
                        {
                            Id = 2,
                            Naziv = "Korisnik",
                            Opis = "Pregled podataka"
                        });
                });

            modelBuilder.Entity("eRestoran.Services.Database.Uplatum", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BrojTransakcije")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<DateTime?>("DatumTransakcije")
                        .HasColumnType("datetime");

                    b.Property<decimal?>("Iznos")
                        .HasColumnType("money");

                    b.Property<int?>("KorisnikId")
                        .HasColumnType("int");

                    b.Property<string>("NacinPlacanja")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id")
                        .HasName("PK__Uplata__3214EC07C865A4BE");

                    b.HasIndex("KorisnikId");

                    b.ToTable("Uplata");
                });

            modelBuilder.Entity("eRestoran.Services.Database.Dojmovi", b =>
                {
                    b.HasOne("eRestoran.Services.Database.Jelo", "Jelo")
                        .WithMany("Dojmovis")
                        .HasForeignKey("JeloId")
                        .HasConstraintName("FK__Dojmovi__JeloId__36B12243");

                    b.HasOne("eRestoran.Services.Database.Korisnici", "Korisnik")
                        .WithMany("Dojmovis")
                        .HasForeignKey("KorisnikId")
                        .HasConstraintName("FK__Dojmovi__Korisni__37A5467C");

                    b.Navigation("Jelo");

                    b.Navigation("Korisnik");
                });

            modelBuilder.Entity("eRestoran.Services.Database.Jelo", b =>
                {
                    b.HasOne("eRestoran.Services.Database.Kategorija", "Kategorija")
                        .WithMany("Jelos")
                        .HasForeignKey("KategorijaId")
                        .HasConstraintName("FK__Jelo__Kategorija__2E1BDC42");

                    b.Navigation("Kategorija");
                });

            modelBuilder.Entity("eRestoran.Services.Database.Korisnici", b =>
                {
                    b.HasOne("eRestoran.Services.Database.Drzava", null)
                        .WithMany("Korisnicis")
                        .HasForeignKey("DrzavaId");

                    b.HasOne("eRestoran.Services.Database.Grad", null)
                        .WithMany("Korisnicis")
                        .HasForeignKey("GradId");
                });

            modelBuilder.Entity("eRestoran.Services.Database.KorisniciUloge", b =>
                {
                    b.HasOne("eRestoran.Services.Database.Korisnici", "Korisnik")
                        .WithMany("KorisniciUloges")
                        .HasForeignKey("KorisnikId")
                        .HasConstraintName("FK__Korisnici__Koris__4316F928");

                    b.HasOne("eRestoran.Services.Database.Uloge", "Uloga")
                        .WithMany("KorisniciUloges")
                        .HasForeignKey("UlogaId")
                        .HasConstraintName("FK__Korisnici__Uloga__440B1D61");

                    b.Navigation("Korisnik");

                    b.Navigation("Uloga");
                });

            modelBuilder.Entity("eRestoran.Services.Database.Narudzba", b =>
                {
                    b.HasOne("eRestoran.Services.Database.Korisnici", "Korisnik")
                        .WithMany("Narudzbas")
                        .HasForeignKey("KorisnikId")
                        .HasConstraintName("FK__Narudzba__Korisn__32E0915F");

                    b.HasOne("eRestoran.Services.Database.Status", "StatusNarudzbe")
                        .WithMany("Narudzbas")
                        .HasForeignKey("StatusNarudzbeId")
                        .HasConstraintName("FK__Narudzba__Status__33D4B598");

                    b.Navigation("Korisnik");

                    b.Navigation("StatusNarudzbe");
                });

            modelBuilder.Entity("eRestoran.Services.Database.StavkeNarudzbe", b =>
                {
                    b.HasOne("eRestoran.Services.Database.Jelo", "Jelo")
                        .WithMany("StavkeNarudzbes")
                        .HasForeignKey("JeloId")
                        .HasConstraintName("FK__StavkeNar__JeloI__3A81B327");

                    b.HasOne("eRestoran.Services.Database.Narudzba", "Narudzba")
                        .WithMany("StavkeNarudzbes")
                        .HasForeignKey("NarudzbaId")
                        .HasConstraintName("FK__StavkeNar__Narud__3B75D760");

                    b.Navigation("Jelo");

                    b.Navigation("Narudzba");
                });

            modelBuilder.Entity("eRestoran.Services.Database.Uplatum", b =>
                {
                    b.HasOne("eRestoran.Services.Database.Korisnici", "Korisnik")
                        .WithMany("Uplata")
                        .HasForeignKey("KorisnikId")
                        .HasConstraintName("FK__Uplata__Korisnik__3E52440B");

                    b.Navigation("Korisnik");
                });

            modelBuilder.Entity("eRestoran.Services.Database.Drzava", b =>
                {
                    b.Navigation("Korisnicis");
                });

            modelBuilder.Entity("eRestoran.Services.Database.Grad", b =>
                {
                    b.Navigation("Korisnicis");
                });

            modelBuilder.Entity("eRestoran.Services.Database.Jelo", b =>
                {
                    b.Navigation("Dojmovis");

                    b.Navigation("StavkeNarudzbes");
                });

            modelBuilder.Entity("eRestoran.Services.Database.Kategorija", b =>
                {
                    b.Navigation("Jelos");
                });

            modelBuilder.Entity("eRestoran.Services.Database.Korisnici", b =>
                {
                    b.Navigation("Dojmovis");

                    b.Navigation("KorisniciUloges");

                    b.Navigation("Narudzbas");

                    b.Navigation("Uplata");
                });

            modelBuilder.Entity("eRestoran.Services.Database.Narudzba", b =>
                {
                    b.Navigation("StavkeNarudzbes");
                });

            modelBuilder.Entity("eRestoran.Services.Database.Status", b =>
                {
                    b.Navigation("Narudzbas");
                });

            modelBuilder.Entity("eRestoran.Services.Database.Uloge", b =>
                {
                    b.Navigation("KorisniciUloges");
                });
#pragma warning restore 612, 618
        }
    }
}
